version: 2.1

orbs:
  ruby: circleci/ruby@0.1.2
  heroku: circleci/heroku@1.2.6 

jobs:
  # deliberately not doing anything in build so we can have a job called test which is what heroku workflow requires
  build:
    working_directory: ~/on_tea_way
    docker:
      # - image: circleci/ruby:2.6.3-stretch-node
      - image: cimg/ruby:2.7.2
        environment:
          PG_HOST: localhost
          PG_USER: circleci
      - image: postgres:13.3
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: on_tea_way_test
          POSTGRES_HOST_AUTH_METHOD: trust
    # executor: ruby/default
    steps:
      - checkout
    #   - run:
    #       name: Which bundler?
    #       command: bundle update
    #   - ruby/bundle-install
  test:
    docker:
      - image: cimg/ruby:2.7.2
        environment:
          PG_HOST: localhost
          PG_USER: circleci
      - image: postgres:13.3
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: on_tea_way_test
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run: bundle install
      - run:
          name: set up DB
          command: |
            bundle exec rake db:create db:schema:load --trace
            bundle exec rake db:migrate
          environment:
              DATABASE_URL: "postgres://circleci@localhost:5432/on_tea_way_test"
      - run: bundle exec rspec spec